{{- define "apigw_app.resources" }}
{{- if .Values.global.apigw.resources }}
{{- $resources := .Values.global.apigw.resources }}
resources:
  limits:
    cpu: {{ $resources.limits.cpu | quote }}
    memory: {{ $resources.limits.memory | quote }}
  requests:
    cpu: {{ $resources.requests.cpu | quote }}
    memory: {{ $resources.requests.memory | quote }}
{{- else }}
resources:
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 400Mi
{{- end }}
{{- end }}
