{{- $cfg := .Values.global.apigw.apigw_app.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigw.apigw_app.configmap.name" . }}
  labels:
    {{- include "apigw.labels" . | nindent 4 }}
data:
  {{ .Values.config_file }}: |
{{ $cfg | mustToPrettyJson | trim | indent 4 }}
