{{- $autoscale := .Values.global.apigw.apigw_app }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-autoscale
  labels:
    {{- include "apigw.labels" . | nindent 4 }}
spec:
  minReplicas: {{ $autoscale.minReplicas }}
  maxReplicas: {{ $autoscale.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "apigw.apigw_app.deployment.name" . }}
  targetCPUUtilizationPercentage: {{ $autoscale.targetCPUUtilizationPercentage | default "60" }}
