{{- if .Values.global.serviceMonitor -}}
{{- if .Values.global.serviceMonitor.enabled -}}
apiVersion: {{ include "common.ServiceMonitor.apiVersion" . }}
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "apigw.labels" . | nindent 4 }}
    {{- include "common.ServiceMonitor.metadata.labes" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      app: {{ .Values.helm.app | quote }}
      tier: {{ .Values.helm.tier | quote }}
  endpoints:
  - path: {{ .Values.prometheusPath | default "/metrics" }}
    targetPort: {{ .Values.global.apigw.apigw_app.config.metrics.listen_port | default "9100" }}
    interval: {{ .Values.prometheusInterval | default "15s" }}
{{- end -}}
{{- end -}}
