{{- $cfg := .Values.global.apigw.apigw_app.config }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apigw.apigw_app.service.name" . }}
  labels:
    {{- include "apigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helm.service_type | quote }}
  selector:
    {{- include "apigw.labels" . | nindent 4 }}
  ports:
    - name: {{ include "apigw.apigw_app.port.callback_server.Name" . }}
      port: {{ include "apigw.apigw_app.port.callback_server.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.callback_server.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.callback_server.Protocol" . }}
    - name: {{ include "apigw.apigw_app.port.api_server.Name" . }}
      port: {{ include "apigw.apigw_app.port.api_server.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.api_server.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.api_server.Protocol" . }}
    - name: {{ include "apigw.apigw_app.port.proxy_server.Name" . }}
      port: {{ include "apigw.apigw_app.port.proxy_server.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.proxy_server.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.proxy_server.Protocol" . }}
    - name: {{ include "apigw.apigw_app.port.health_server.Name" . }}
      port: {{ include "apigw.apigw_app.port.health_server.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.health_server.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.health_server.Protocol" . }}
    - name: {{ include "apigw.apigw_app.port.sync_api_server.Name" . }}
      port: {{ include "apigw.apigw_app.port.sync_api_server.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.sync_api_server.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.sync_api_server.Protocol" . }}
{{- if .Values.global.serviceMonitor }}
{{- if .Values.global.serviceMonitor.enabled }}
    - name: {{ include "apigw.apigw_app.port.metrics.Name" . }}
      port: {{ include "apigw.apigw_app.port.metrics.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.metrics.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.metrics.Protocol" . }}
{{- end }}
{{- end }}
{{- if .Values.global.apigw.connect_enabled }}
    - name: {{ include "apigw.apigw_app.port.connect_server_tunnel.Name" . }}
      port: {{ include "apigw.apigw_app.port.connect_server_tunnel.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.connect_server_tunnel.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.connect_server_tunnel.Protocol" . }}
    - name: {{ include "apigw.apigw_app.port.connect_server_proxy.Name" . }}
      port: {{ include "apigw.apigw_app.port.connect_server_proxy.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.connect_server_proxy.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.connect_server_proxy.Protocol" . }}
{{- end }}
{{- if .Values.global.apigw.apigw_app.config.task_api_server }}
    - name: {{ include "apigw.apigw_app.port.task_api_server.Name" . }}
      port: {{ include "apigw.apigw_app.port.task_api_server.Number" . }}
      targetPort: {{ include "apigw.apigw_app.port.task_api_server.Number" . }}
      protocol: {{ include "apigw.apigw_app.port.task_api_server.Protocol" . }}
{{- end }}