global:
  # Product name, using in labes
  product: "api-gw"
  # Type of repo with images on docker-hub.middleware.biz
  repotype: "public"

  db:
    # Current helm chart support only external DB.
    # Before install chart, we need to create PostgreSQL 13.x database "apigw", create user "apigw_user" with password and set this user as owner for database.
    # Change DB_HOST to actual database address.
    # Change APP_DB_PASSWORD to database user apigw_user password.
    internal: false
    secret:
    ## true - secret will be created automaticaly with provided values
    ## false - secret should be created manualy
      name: "postgresql-secret"
      create: false
      data:
        dbname: "apigw"
        dbhost: "DB_HOST"
        dbport: "5432"
        dbuser: "apigw_user"
        dbpwd: "APP_DB_PASSWORD"
    bouncer: false
    bouncer_minReplicas: 2
    bouncer_maxReplicas: 10
    bouncer_resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    bouncer_log_level: debug

  release:
    name: 'apigw_app'
    helm:
      enabled: true
      chart:
        version: '1.0.0'
        description: 'The apigw application'
      context: 'apigw-prod-k8s'
      namespace: 'apigw-prod'
      release: 'pre'
      deploy: ['apigw', 'apigw_migrations', 'postgresql_credentials', 'kube']
    require:
      apigw: '1.4.0'
      apigw_migrations: '1.4.0'
      kube: '3.0.5'
      postgresql_credentials: '3.0.5'
    db:
      internal: false
      bouncer: false
    postgresql_credentials:
      apigw:
        username: 'apigw_user'
        password: 'APP_DB_PASSWORD'
        host: 'DB_HOST'
        port: 5432
    deploymentStrategy:
      type: RollingUpdate

    frontend:
      image: 'docker-hub.middleware.biz/public/apigw/apigw-frontend'
      tag: "1.0.1"
      pullPolicy: IfNotPresent
      port: 80
      host: "apigw.example.com"
      autoscaling:
        enabled: false
        minReplicas: 2
        maxReplicas: 10

  apigw_migrations:
    config:
      migrate:
        admin_username: 'apigw_user'
        admin_password: 'APP_DB_PASSWORD'
        migrator_username: 'apigw_user'
        migrator_password: 'APP_DB_PASSWORD'
        app_username: 'apigw_user'
        app_password: 'APP_DB_PASSWORD'
        owner_username: 'apigw_user'
        owner_password: 'APP_DB_PASSWORD'
        host: 'DB_HOST'
        port: 5432
        db: 'apigw'
      helm:
        image_pull_secrets: []
        # image_pull_secrets: ['registry-secret']
  imagePullSecrets: {}
    # name: registry-secret

  ingress:
    className:
apigw:
  image: 'docker-hub.middleware.biz/public/apigw/apigw'
  config:
    callback_server:
      aes_key: '1975664b67ac0c9f793d594e5b0ea16d08a2a425b4554a603b42cea4a84a4997'
      aes_nonce: '2551dc73dbe90a057c2c6876'
      host: 'cb-apigw.example.com'
      port: 0
      schema: 'https'
      base_path: '/callback'
      internal_host: '${INTERNAL_HOST}'
      listen_host: '0.0.0.0'
      listen_port: 8070
      read_timeout_sec: 30
    db:
      dsn: 'postgres://${APIGW_POSTGRESQL_USERNAME}:${APIGW_POSTGRESQL_PASSWORD}@${APIGW_POSTGRESQL_HOST}:${APIGW_POSTGRESQL_PORT}/apigw?sslmode=disable&binary_parameters=yes'
    single_account:
      enabled: true
      # Single-account domain
      http_host: 'https://account.example.com'
      # Single-account client id, check README.md file
      client_id: 'SA_CLIENT_ID'
      # Single-account client secret, check README.md file
      client_secret: 'SA_CLIENT_SECRET'
      # Apigw UI domain
      redirect_http_host: 'https://apigw.example.com/'
    api_server:
      listen_host: '0.0.0.0'
      listen_port: 8080
      cors:
        allowed_origins: ['*']
    proxy_server:
      listen_host: '0.0.0.0'
      listen_port: 8090
      host: 'apigw.example.com'
      host_delimiter: '.'
      ready_path: '/ready'
      corezoid:
        # Corezoid apikey login
        admin_login: 777
        # Corezoid apikey secret
        admin_secret: 'NHpUvs1AbiP9GO0FKuxVL5fxzTgP5PFrwBw4Ndp4BaJL8ZT6FE'
        # Corezoid domain
        http_host: 'https://example.com'
    health_server:
      listen_host: '0.0.0.0'
      listen_port: 8060
    prometheus:
      enabled: true
      type: 'scrape'
      metrics_host: '0.0.0.0'
      metrics_port: 9100
    metrics:
      add_path_label: true
      add_process_label: true
      add_api_label: true
  helm:
    debug_container: false
    image_pull_policy: 'Always'
    image_pull_secrets: []
    service_type: 'ClusterIP'
    ingress:
      enabled: true
      name: 'apigw-ingress'
      api_version: 'networking.k8s.io/v1'
      annotations:
        kubernetes.io/ingress.class: 'nginx'
      rules:
        - host: 'api-apigw.example.com'
          http:
            - path: '/'
              pathType: 'Prefix'
              service:
                name: 'apigw-service'
                port:
                  number: 8080
        - host: 'cb-apigw.example.com'
          http:
            - path: '/'
              pathType: 'Prefix'
              service:
                name: 'apigw-service'
                port:
                  number: 8070
        - host: '*.apigw.example.com'
          http:
            - path: '/'
              pathType: 'Prefix'
              service:
                name: 'apigw-service'
                port:
                  number: 8090
        - host: 'apigw.example.com'
          http:
            - path: '/'
              pathType: 'Prefix'
              service:
                name: 'frontend-service'
                port:
                  number: 80
    resources:
        limits:
            cpu: '500m'
            memory: '500M'
        requests:
            cpu: '200m'
            memory: '200M'
    max_replicas: 3
    min_replicas: 2
apigw_migrations:
  config:
    migrate:
      migrator_username: 'apigw_user'
      migrator_password: 'APP_DB_PASSWORD'
      app_username: 'apigw_user'
      app_password: 'APP_DB_PASSWORD'
      owner_username: 'apigw_user'
      host: 'DB_HOST'
      port: 5432
      db: 'apigw'
    helm:
      image_pull_secrets: []
postgresql_credentials:
  apigw:
    username: 'apigw_user'
    password: 'APP_DB_PASSWORD'
    host: 'DB_HOST'
    port: 5432
