{{- if and (hasKey .Values.global "valkey") (not (empty .Values.global.valkey)) }}
{{- if .Values.global.valkey.use }}
{{- if .Values.global.networkPolicy }}
{{- if .Values.global.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apigw-valkey-policy
  labels:
    {{- include "apigw.valkey.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      tier: {{ .Values.appName }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              tier: apigw
      ports:
        - protocol: TCP
          port: {{ .Values.appPort }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}