component_name: apigw
appName: apigw

require: {}

include:
  kube: '2.0.2' # 2.0-dev

helm:
  enabled: true
  app: apigw
  tier: apigw
  chart:
    version: "2.2.10"
    description: "The API Gateway service."

config_file: apigw.json
image: "hub.corezoid.com/apigw/apigw"
