component_name: apigw_migratons
appName: apigw_migratons

require: {}

include:
  migrations: '3.0.5' # 3.0.x

helm:
  enabled: true
  app: apigw
  tier: migrations
  global: false
  chart:
    version: "0.1.0"
    description: The component provides apigw migrations

dir: "/migrations/migrations"
image: "docker-hub.middleware.biz/apigw/apigw-migrations"
