{{- if eq .Values.global.redis.internal true }}
apiVersion: v1
kind: Service
metadata:
  name: apigw-{{ .Values.appName }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.appPort }}
    targetPort: {{ .Values.appPort }}
  selector:
    {{- include "redis.labels" . | nindent 4 }}
{{- end }}
