apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
{{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
{{- include "frontend.labels" . | nindent 6 }}
  ports:
  - port: {{ .Values.appPort }}
    targetPort: {{ .Values.appPort }}
    protocol: TCP
    name: http
