{{- if and (hasKey .Values.global "valkey") (not (empty .Values.global.valkey)) }}
{{- if not .Values.global.valkey.use }}
{{- if eq .Values.global.redis.internal true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-redis-deployment
  labels:
    {{- include "apigw.redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "apigw.redis.labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-redis.yaml") . | sha256sum }}
      labels:
        {{- include "apigw.redis.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.global.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
      {{- end }}
      containers:
      - name: master
        image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "redis-cli -h localhost ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "redis-cli -h localhost ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - name: app
          containerPort: {{ .Values.appPort }}
          protocol : TCP
        volumeMounts:
          - name: redisconfig
            mountPath: /usr/local/etc/redis
      volumes:
        - name: redisconfig
          configMap:
            name: apigw-redis-config
      {{- with .Values.global.apigw.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.apigw.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
