{
 "title": "ApiGW dashboard",
 "tags": [
  "simulator",
  "apigw"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(proxy_count_paths,namespace)"
    }
   },
   {
    "name": "path",
    "label": "proxy: path",
    "query": {
     "query": "label_values(proxy_http_request_duration_seconds_count,path)"
    }
   },
   {
    "name": "login",
    "label": "syncAPI: login",
    "query": {
     "query": "label_values(sync_api_http_request_duration_seconds_count,login)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPM",
   "type": "timeseries",
   "description": "Total requests per minute",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code) (increase(proxy_http_request_duration_seconds_count{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(proxy_http_request_duration_seconds_bucket{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(proxy_http_request_duration_seconds_bucket{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(proxy_http_request_duration_seconds_sum{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval])) * 1 / sum(rate(proxy_http_request_duration_seconds_count{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "4xx/5xx errors percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (new_code) (\n  label_replace(\n    rate(proxy_http_request_duration_seconds_count{code=~'4..|5..',path=~\"$path\"}[$__range]),\n    \"new_code\",\n    \"${1}xx\",\n    \"code\",\n    \"(^\\\\d).+\"\n  )\n) / \nscalar(sum(rate(proxy_http_request_duration_seconds_count{path=~\"$path\"}[$__range]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code, method, path) (increase(proxy_http_request_duration_seconds_count{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval])) > 0",
     "legendFormat": "{{code}}: {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Latency per API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by(method, path) (increase(proxy_http_request_duration_seconds_sum{namespace=\"$namespace\", path=~\"$path\"}[5m])) > 0) / (sum by(method, path) (increase(proxy_http_request_duration_seconds_count{namespace=\"$namespace\", path=~\"$path\"}[5m])) > 0)",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Loaded paths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "proxy_count_paths{namespace=\"$namespace\"}",
     "legendFormat": "paths"
    }
   ]
  },
  {
   "title": "SyncAPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM",
     "type": "timeseries",
     "description": "Total requests per minute",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (code) (increase(sync_api_http_request_duration_seconds_count{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(sync_api_http_request_duration_seconds_bucket{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval])) by (le)) * 1",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(sync_api_http_request_duration_seconds_bucket{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval])) by (le)) * 1",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "sum(rate(sync_api_http_request_duration_seconds_sum{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval])) * 1 / sum(rate(sync_api_http_request_duration_seconds_count{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "4xx/5xx errors percentage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (new_code) (\n  label_replace(\n    rate(sync_api_http_request_duration_seconds_count{code=~'4..|5..',login=~\"$login\"}[$__range]),\n    \"new_code\",\n    \"${1}xx\",\n    \"code\",\n    \"(^\\\\d).+\"\n  )\n) / \nscalar(sum(rate(sync_api_http_request_duration_seconds_count{login=~\"$login\"}[$__range]))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPM per login",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(code, login) (increase(sync_api_http_request_duration_seconds_count{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval])) > 0",
       "legendFormat": "{{code}}: login - {{login}}"
      }
     ]
    },
    {
     "title": "Latency per login",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(sum by(login) (increase(sync_api_http_request_duration_seconds_sum{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval])) > 0) / (sum by(login) (increase(sync_api_http_request_duration_seconds_count{namespace=\"$namespace\", login=~\"$login\"}[$__rate_interval])) > 0)",
       "legendFormat": "login - {{login}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tunnels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected online",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tunnelsConnected{namespace=\"$namespace\"}",
       "legendFormat": "sockets"
      }
     ]
    },
    {
     "title": "Requests (connections)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(tunnelsProxyOk{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(increase(tunnelsProxyToPod{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "proxyToPod"
      },
      {
       "expr": "sum(increase(tunnelsProxyNotFound{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "not_found"
      }
     ]
    }
   ]
  }
 ]
}