{{- if .Values.global.ingressPublic -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress-public
  annotations: {{ toYaml .Values.global.ingressPublic.annotations | nindent 4 }}
spec:
  {{- if and .Values.global.ingressPublic.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingressPublic.className }}
  {{- end }}
  rules:
    - host: '*.{{ include "apigw.hosts.proxy_server" . }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.proxy_server.Number" . }}
{{- if .Values.global.apigw.connect_enabled }}
    - host: {{ include "apigw.hosts.connect_server_tunnel" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.connect_server_tunnel.Number" . }}
    - host: '*.{{ include "apigw.hosts.connect_server_tunnel" . }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.connect_server_proxy.Number" . }}
{{- end }}
{{- end -}}