{{- $global := .Values.global -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations: {{ toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  {{- if and .Values.global.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "apigw.hosts.api_server" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.api_server.Number" . }}
    - host: {{ include "apigw.hosts.callback_server" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.callback_server.Number" . }}
{{- if not .Values.global.ingress_public }}
    - host: '*.{{ include "apigw.hosts.proxy_server" . }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.proxy_server.Number" . }}
{{- end }}
    - host: {{ include "apigw.hosts.sync" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.sync_api_server.Number" . }}
{{- if .Values.global.apigw.connect_enabled }}
    - host: {{ include "apigw.hosts.connect_server_tunnel" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.connect_server_tunnel.Number" . }}
    - host: '*.{{ include "apigw.hosts.connect_server_tunnel" . }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.connect_server_proxy.Number" . }}
{{- end }}
{{- if .Values.global.apigw.apigw_app.task_api_server_subDomain }}
    - host: {{ include "apigw.hosts.task_api_server" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "apigw.apigw_app.service.name" . }}
                port:
                  number: {{ include "apigw.apigw_app.port.task_api_server.Number" . }}
{{- end }}
