{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations: {{ toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ include "apigw.hosts.api_server" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw-service
                port:
                  number: {{ .Values.global.apigw.apigw_app.config.api_server.listen_port }}
    - host: {{ include "apigw.hosts.callback_server" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw-service
                port:
                  number: {{ .Values.global.apigw.apigw_app.config.callback_server.listen_port }}
    - host: '*.{{ include "apigw.hosts.proxy_server" . }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw-service
                port:
                  number: {{ .Values.global.apigw.apigw_app.config.proxy_server.listen_port }}
    - host: {{ include "apigw.hosts.frontend" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw-frontend-service
                port:
                  number: 80
    - host: {{ include "apigw.hosts.sync" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw-service
                port:
                  number: {{ .Values.global.apigw.apigw_app.config.sync_api_server.listen_port }}