{{- if .Values.global.redis.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apigw.redisSecretName" . | quote }}
  labels:
    app: {{ .Values.global.product }}
    tier: "redis"
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.redis.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
