{{- if .Values.global.db.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apigw.postgresSecretName" . | quote }}
  labels:
    app: {{ .Values.global.product }}
    tier: "postgres"
    release: {{ .Release.Name | quote }}
  annotations:
    {{- include "apigw.postgresSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.db.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}

---
{{- if .Values.global.db_settings }}
{{- if .Values.global.db_settings.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apigw.postgresSettingsSecretName" . | quote }}
  labels:
    app: {{ .Values.global.product }}
    tier: "postgres"
    release: {{ .Release.Name | quote }}
  annotations:
    {{- include "apigw.postgresSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.db_settings.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
