{{- if .Values.global.valkey }}
{{- if .Values.global.valkey.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apigw.valkeySecretName" . | quote }}
  labels:
    app: {{ .Values.global.product }}
    tier: "valkey"
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.valkey.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
