apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-nginx-configmap
  labels:
{{- include "apigw-frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes auto;
    error_log /dev/stdout;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  32000;
      multi_accept on;
    }

    http {
      client_max_body_size 25m;
      server_names_hash_bucket_size 128;
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      log_format up_log '$server_addr\t$server_port\t$http_x_forwarded_for\t$time_iso8601\tforward-to $upstream_addr\t$request\t$status\t$body_bytes_sent\t$request_time\t$upstream_response_time\t$http_referer\t$http_user_agent\t$http_cookie\t$host';
      access_log /dev/stdout up_log;

      sendfile        on;
      tcp_nopush     on;

      server_tokens   off;
      # disable buffering
      proxy_buffering off;
      proxy_max_temp_file_size 0;
      keepalive_timeout  65;
      gzip on;
      gzip_types text/css application/x-javascript text/xml application/xml application/xml+rss text/plain application/javascript text/javascript application/json image/png image/svg+xml;
      gzip_proxied any;
      include /etc/nginx/conf.d/*.conf;
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-site-configmap
  labels:
{{- include "apigw-frontend.labels" . | nindent 4 }}
data:
  apigw_{{ .Values.appName }}.conf: |
    server {

      access_log /dev/stdout main;
      error_log  /dev/stdout;

      server_tokens off;
      listen  {{ include "apigw_frontend.appPort" . }};
      charset utf8;

      location / {
        root /app/www/apigw/;
        try_files $uri /index.html;
      }

      location /api/ {
        client_max_body_size 50m;
        proxy_set_header Connection "keep-alive";
        proxy_pass http://{{ include "apigw.apigw_app.service.name" . }}:{{ include "apigw.apigw_app.port.api_server.Number" . }}/;
      }
    }
